name: Run Api and Web UI tests for Hillel QAuto

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          pytest -v --alluredir=allure-results
        env:
          WEB_USER: ${{secrets.WEB_USER}}
          WEB_PASS: ${{secrets.WEB_PASS}}

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        #uses: ./allure-report-action
        if: always()
        #id: allure-report
        with:
          allure_results: allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history
          keep_reports: 5

      - name: Deploy report to Github Pages
        if: always()
        #if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-history

      - name: Get Allure Report URL
        run: echo "ALLURE_URL=https://xslmur.github.io/login_auto_testing/${{ github.run_number }}/" >> $GITHUB_ENV

      - name: Update README with Allure Report URL
        run: |
          sed -i "s#<!-- ALLURE_REPORT -->#Check out the latest [Allure Report]($ALLURE_URL)#" README.md

      - name: Commit README.md changes
        run: |
          git config --local user.email "xslmr@proton.me"
          git config --local user.name "xslmr"
          git add README.md
          git commit -m "Update Allure Report URL"
          git push

#        env:
#          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PUBLISH_BRANCH: gh-pages
#          PUBLISH_DIR: allure-history
