name: run qauto tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        uses: dariocurr/pytest-summary@main
        with:
          paths: test_login_UI.py
          options: --quiet
          # show the summary for both successful and failed tests
          show: all
        env:
          WEB_USER: ${{secrets.WEB_USER}}
          WEB_PASS: ${{secrets.WEB_PASS}}
