name: run qauto tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.11"
      - name: Run tests
        uses: dariocurr/pytest-summary@main
        with:
          paths: test_qauto.py
          # show the summary for both successful and failed tests
          show: all
